C51INC = C:\Keil\C51\INC\Nuvoton\;C:\Keil\C51\INC\
C51LIB=C:\Keil\C51\LIB
CPU_TYPE=N76E003
CPU_VENDOR=Nuvoton
UV2_TARGET=Simulator
CPU_XTAL=0x00F42400
all:
	@echo '---------------------------'
	"C:\Keil\C51\BIN\C51.EXE" @HELLO.__i
	"C:\Keil\C51\BIN\BL51.EXE" @HELLO.lnp
	"C:\Keil\C51\BIN\OH51.EXE" "HELLO" 
